### ISSUE TITLE
Stop the download of the snap package.

### ISSUE THREAD

**Issue by sidahmed-malaoui** [snapcore/snapd#2538]
When using the command `snap install some_package`, the package will continue to download even if the command is canceled.

Can you implement a feature to stop the download when the installing command is canceled !!

**Comment by zyga** [comment]
I think this was already considered earlier and it got implemented. Can you tell me which version of snapd you are using now? Thanks.

**Comment by sidahmed-malaoui** [comment]
This is the output of the command `snap --version` : 
>snap    2.17.1ubuntu1
snapd   2.17.1ubuntu1
series  16
ubuntu  16.04

**Comment by zyga** [comment]
Thanks, I think this is fixed in 2.20.1 that is supposed to get out of proposed soon. Can you try (if you want to) the package in xenail-proposed to see if this is fixed? This wiki page has some useful information. I would recommend that you enable proposed selectively for just `snapd` and `snap-confine`. https://wiki.ubuntu.com/Testing/EnableProposed

**Comment by sidahmed-malaoui** [comment]
Awesome, just tested it, and it works great. Thanks.
