### ISSUE TITLE
interfaces: connect tun-based serial port

### ISSUE THREAD

**Issue by mrsinghgit** [snapcore/snapd#2557]
We are trying to get a head start on Core Snappy working with our RF Mesh network card.  It connects over serial and needs to be available at boot.  The documentation showed a serial-port interface available, but in Core16 we do not see that interface and cannot connect successfully over serial.

**Please find the details about the issue we are facing currently related to Serial Port plug/interface issue with Ubuntu-core 16.04 -**
We were successfully able to build and install a snap using our existing binaries(for both armhf and x86 architecture) . The snap has the permission to use a serial port(added serial-port plug to each binaries). 

While executing the snap using the command below:
sudo ssn-iotr.tunnccd -i /dev/ttyS0 -T tun6 -D ::/0 -m info -M i -b &
 
We would expect the tun6 interface to be created but it is not, we can see it trying to create a tun interface, but apparmor security log shows serial i/o requests are being denied.  

**Here is the syslog entry after running the above command:**
`Dec 20 17:22:23 localhost tunnccd[1348]: tunnccd version 04.01.82.03 (Silver Spring Networks, Inc.): inittab mode
Dec 20 17:22:23 localhost kernel: [  599.954802] audit: type=1400 audit(1482254543.254:20): apparmor="ALLOWED" operation="mknod" profile="snap.ssn-iotr.tunnccd" name="/run/tunnccd.pid" pid=1348 comm="tunnccd" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Dec 20 17:22:23 localhost kernel: [  599.954893] audit: type=1400 audit(1482254543.254:21): apparmor="ALLOWED" operation="open" profile="snap.ssn-iotr.tunnccd" name="/run/tunnccd.pid" pid=1348 comm="tunnccd" requested_mask="wc" denied_mask="wc" fsuid=0 ouid=0
Dec 20 17:22:23 localhost kernel: [  599.956239] audit: type=1400 audit(1482254543.254:22): apparmor="ALLOWED" operation="open" profile="snap.ssn-iotr.tunnccd" name="/dev/ttyS0" pid=1348 comm="tunnccd" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
Dec 20 17:22:23 localhost tunnccd[1348]: tunnccd version 04.01.82.03 (Silver Spring Networks, Inc.)
Dec 20 17:22:23 localhost kernel: [  599.956605] audit: type=1400 audit(1482254543.258:23): apparmor="ALLOWED" operation="open" profile="snap.ssn-iotr.tunnccd" name="/dev/net/tun" pid=1348 comm="tunnccd" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0
Dec 20 17:22:23 localhost kernel: [  599.956690] audit: type=1400 audit(1482254543.258:24): apparmor="ALLOWED" operation="capable" profile="snap.ssn-iotr.tunnccd" pid=1348 comm="tunnccd" capability=12  capname="net_admin"
Dec 20 17:22:23 localhost tunnccd[1348]: ncc_open: speed: 115200
Dec 20 17:22:23 localhost tunnccd[1348]: tun_alloc: Tun device is /dev/tun6
Dec 20 17:22:23 localhost tunnccd[1348]: tunnel open: tun6 opened: fd: 2
`
 
We tried a few variations of the 'snap connect' command, but in Core16 we do not see the serial interface and cannot connect successfully over serial. 

Over IRC one of the developer told that this behavior is due to **missing hotplugging serial-interface in current(latest) version of snapcraft and this feature might be available in  @January**.

**Comment by jamiedbennett** [comment]
Hi,

Hotpluggable interfaces are definitely on our radar but because of the wide variety of devices and possible permutations this is tricky. We will be working on it during the coming months but there is no definite availability date until the initial investigation and design are complete. In the meantime I will discuss the possibility of enabling tun* in the serial-port interface with our security team to see what the possibilities are.

Regards,
Jamie.

**Comment by manik-taneja** [comment]
Feedback from engineering-

-------------
Looking at the log output, it appears the snap is in devmode (since everything
says ALLOWED). If the device is not being correctly created in devmode, that
would indicate that apparmor and seccomp are not causing the problem.

To solve the devmode issues that were reported:
- tunnccd.pid needs to be put in SNAP_DATA or SNAP_COMMON
- /dev/ttyS0 needs to be exposed to the serial-port interface so that the
  tunnccd snap can access it. This can be done today using a gadget snap (ask 
  the CE team for details and working examples)
- access to /dev/net/tun needs to be granted. The tunnccd snap needs to
  'plugs: [ network-control ]'
- /dev/tun* needs to be allowed somewhere. We don't need dynamic plugging for
  that though. These devices are created by opening /dev/net/tun and issuing an
  ioctl(), then the device is created at /dev/tunN or /dev/tapN[1]. As a result,
  I think we need to adjust the network-control interface to allow
    /dev/tun[0-9]* rw,
    /dev/tap[0-9]* rw,

What we will need hotplugging for is udev tagging these so that the devices are
added to the device cgroup for the snap when the devices are created and
removed. So long as the tunnccd snap isn't plugging interfaces that use the udev
backend though, the apparmor change I listed above will be enough.

As it happens, I am working on various policy updates for 2.21 so I'll add the
above two rules to the interface as part of that work.

Feel free to copy/paste any or all of this email into the bug report.

[1]http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documenta
tion/networking/tuntap.txt
-----------

**Comment by jdstrand** [comment]
FYI, from https://github.com/snapcore/snapd/pull/2590:

```
    interfaces/network-control: allow rw on /dev/tun* and /dev/tap*

    /dev/tun* and /dev/tap* devices are created by opening /dev/net/tun and issuing
    an ioctl(), so it makes sense to add these devices to the network-control
    interface. Note that since these devices are dynamically created and removed,
    we need dynamic hotplugging support in snapd. This PR does not attempt to
    address hotplugging since that has not been implemented yet.
```

**Comment by mrsinghgit** [comment]
Thanks @manik-taneja and @jdstrand for the detailed feedback. As suggested we would like to try the gadget snap approach in order to expose /dev/ttyS0 to the serial port interface for tunnccd snap to access it. 
It would be great if we can have the **working example of a gadget snap with access to serial interface**.

**Comment by niemeyer** [comment]
@mrsinghgit  We need better docs indeed. Meanwhile, you can find some examples in the test suite:

https://github.com/snapcore/snapd/blob/master/interfaces/builtin/serial_port_test.go

**Comment by niemeyer** [comment]
@mrsinghgit Please let us know how it goes, btw. We know docs for these details are lacking, so this can be a bit frustrating, but we can compensate by helping out here.

**Comment by jdstrand** [comment]
FYI, https://github.com/snapcore/snapd/pull/2590 is merged and the changes to network-control will be in snapd 2.21.

**Comment by mrsinghgit** [comment]
@niemeyer I am wondering how to use this example. Kindly guide. 

Also can I have one end to end gadget snap example or step by step tutorial. It can be of any device not necessarily serial port as I want to kickstart writing gadget snap. Please bear with me as I am new to snap development.

**Comment by niemeyer** [comment]
Just as an initial kick off, the examples there show several ways to add a serial slot to a snap. You need to do something simliar in the gadget snap. There really isn't much to it. 

If you need further info, may I ask you to please send an email with the details you're looking for to the snapcraft mailing list:

    https://lists.snapcraft.io/mailman/listinfo/snapcraft

After subscription, email to:

    snapcraft@lists.snapcraft.io

Will be easier to follow up and more people will collaborate there than here.
